openapi: "3.0.0"

info:
  description: "PhoneBook API"
  version: "1.0.0"
  title: "PhoneBook"

servers:
  - url: "/api"

tags:
  - name: "contacts"
    description: "Everything about contacts"

paths:

  /contacts:
    get:
      tags:
        - "contacts"
      summary: "Get contacts"
      parameters:
        - in: query
          name: orderBy
          schema:
            type: string
        - in: query
          name: orderDirection
          schema:
            type: string
        - in: query
          name: count
          schema:
            type: string
        - in: query
          name: offset
          schema:
            type: string
      responses:
        200:
          description: "Contacts array"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Contact"
    post:
      tags:
        - "contacts"
      summary: "Create contact"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: "object"
              properties:
                name:
                  type: "string"
                phone:
                  type: "string"
              example:
                name: "Gregory"
                phone: "876876876876"
      responses:
        200:
          description: "Contact created"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Contact"

  /contacts/{id}:
    parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
        description: "Contact id"
    put:
      tags:
        - "contacts"
      summary: "Update contact by id"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: "object"
              properties:
                name:
                  type: "string"
                phone:
                  type: "string"
      responses:
        200:
          description: "Contact updated"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Contact"
    delete:
      tags:
        - "contacts"
      summary: "Delete contact by id"
      responses:
        200:
          description: "Contact deleted"

  /contacts/importFile:
    post:
      tags:
        - "contacts"
      summary: "Import contacts from file"
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                strategy:
                  type: string
      responses:
        200:
          description: "File imported"

  /contacts/exportFile:
    post:
      tags:
        - "contacts"
      summary: "Export contacts to file"
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                strategy:
                  type: string
      responses:
        200:
          description: "File download"

components:
  schemas:
    Contact:
      type: "object"
      required:
        - id
      properties:
        id:
          type: "integer"
        name:
          type: "string"
        phone:
          type: "string"
        createdAt:
          type: "string"
        updatedAt:
          type: "string"

externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"