export const LOAD_CONTACTS_REQUEST = 'contacts/LOAD_CONTACTS_REQUEST';
export const LOAD_CONTACTS_SUCCESS = 'contacts/LOAD_CONTACTS_SUCCESS';

export const CREATE_CONTACT_REQUEST = 'contacts/CREATE_CONTACT_REQUEST';

export const UPDATE_CONTACT_REQUEST = 'contacts/UPDATE_CONTACT_REQUEST';
export const UPDATE_CONTACT_SUCCESS = 'contacts/UPDATE_CONTACT_SUCCESS';

export const DELETE_CONTACT_REQUEST = 'contacts/DELETE_CONTACT_REQUEST';
export const DELETE_CONTACT_SUCCESS = 'contacts/DELETE_CONTACT_SUCCESS';

export const IMPORT_CONTACTS_FROM_FILE_REQUEST = 'contacts/IMPORT_CONTACTS_FROM_FILE_REQUEST';

export const EXPORT_CONTACTS_TO_FILE_REQUEST = 'contacts/EXPORT_CONTACTS_TO_FILE_REQUEST';